// Carbon icon mapping - commonly used icons
export const carbonIcons = [
  // Navigation
  'dashboard',
  'home',
  'search',
  'settings',
  'user',
  'notification',
  'menu',
  'close',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'arrow-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'chevron-down',
  
  // Actions
  'add',
  'edit',
  'delete',
  'save',
  'cancel',
  'refresh',
  'download',
  'upload',
  'share',
  'copy',
  'paste',
  'cut',
  'undo',
  'redo',
  
  // Data & Analytics
  'chart-line',
  'chart-bar',
  'chart-pie',
  'chart-scatter',
  'analytics',
  'data-vis-1',
  'data-vis-2',
  'data-vis-3',
  'data-vis-4',
  'table',
  'list',
  'grid',
  
  // Communication
  'email',
  'chat',
  'phone',
  'video',
  'microphone',
  'camera',
  'send',
  'reply',
  'forward',
  
  // Files & Documents
  'document',
  'folder',
  'file',
  'image',
  'video-camera',
  'audio',
  'pdf',
  'word',
  'excel',
  'powerpoint',
  
  // Security
  'lock',
  'unlock',
  'shield',
  'key',
  'password',
  'security',
  'vpn',
  'firewall',
  
  // Development
  'code',
  'terminal',
  'api',
  'database',
  'server',
  'cloud',
  'container',
  'kubernetes',
  'docker',
  
  // Business
  'user-multiple',
  'group',
  'organization',
  'building',
  'location',
  'calendar',
  'time',
  'money',
  'shopping-cart',
  'shopping-bag',
  
  // Status
  'checkmark',
  'error',
  'warning',
  'information',
  'help',
  'question-mark',
  'success',
  'error-filled',
  'warning-filled',
  'information-filled',
  
  // System
  'settings-adjust',
  'settings-view',
  'settings-check',
  'settings-advanced',
  'system',
  'monitor',
  'laptop',
  'mobile',
  'tablet',
  'desktop',
  
  // Weather & Time
  'sun',
  'moon',
  'cloud',
  'rain',
  'snow',
  'wind',
  'temperature',
  'clock',
  'timer',
  'alarm',
  
  // Social
  'facebook',
  'twitter',
  'linkedin',
  'github',
  'youtube',
  'instagram',
  'slack',
  'discord',
  
  // Utilities
  'filter',
  'sort',
  'zoom-in',
  'zoom-out',
  'full-screen',
  'exit-full-screen',
  'maximize',
  'minimize',
  'resize',
  'move',
  'rotate',
  'scale',
  
  // Map & Drawing Tools
  'layers',
  'opacity',
  'choropleth-map',
  'ruler-alt',
  'draw',
  'code-block',
  'printer',
  
  // Accessibility
  'user-accessibility',
  'user-accessibility-color-filled',
  'system-theme',
  'format-text-size',
  'format-text-family',
  'format-palette',
  'operations-reset',
  'file-download',
  'file-upload',
  'navigation-close',
  
  // Settings & Actions
  'save',
  'refresh',
  'delete',
  
  // Carbon Design System Icons
  'weather-Lightning',
  'status-information',
  'system-workflow-information',
  'Ai',
  'format-image',

  // Additional 300 Carbon icons
  '4-k',
  '4-kfilled',
  'accept-action-usage',
  'accessibility-alt',
  'accessibility-color',
  'accessibility-color-filled',
  'accumulation-ice',
  'accumulation-precipitation',
  'action-definition',
  'action-usage',
  'activity',
  'add-alt',
  'add-child-node',
  'add-filled',
  'add-large',
  'add-parent-node',
  'alarm-add',
  'account',
  'gateway-user-access',
  'multiuser-device',
  'person',
  'person-favorite',
  'two-person-lift',
  'user-access',
  'user-activity',
  'user-admin',
  'user-avatar',
  'user-avatar-filled',
  'user-avatar-filled-alt',
  'user-certification',
  'user-favorite',
  'user-favorite-alt',
  'user-favorite-alt-filled',
  'user-filled',
  'accumulation-rain',
  'ai-business-impact-assessment',
  'ai-financial-sustainability-check',
  'ai-generate',
  'ai-governance-lifecycle',
  'ai-governance-tracked',
  'ai-governance-untracked',
  'ai-label',
  'ai-launch',
  'ai-recommend',
  'airline-digital-gate',
  'airline-manage-gates',
  'airline-passenger-care',
  'airline-rapid-board',
  'airplay',
  'airplay-filled',
  'airport-location',
  'accumulation-snow',
  'decision-tree',
  'earth',
  'earth-americas',
  'earth-americas-filled',
  'earth-europe-africa',
  'earth-europe-africa-filled',
  'earth-filled',
  'earth-southeast-asia',
  'earth-southeast-asia-filled',
  'earthquake',
  'ibm-zenvironments-dev-sec-ops',
  'list-tree',
  'moonrise',
  'moonset',
  'palm-tree',
  'radar-weather',
  'add-comment',
  'calls',
  'calls-all',
  'calls-incoming',
  'chat-bot',
  'chat-launch',
  'chat-off',
  'chat-operational',
  'comments',
  'headphones',
  'logo-snapchat',
  'logo-wechat',
  'message-queue',
  'notification-counter',
  'notification-filled',
  'notification-new',
  'notification-off',
  'aggregator-count-rows',
  'aggregator-recalculation',
  'agriculture-analytics',
  'analytics-custom',
  'analytics-reference',
  'business-metrics',
  'chart-area',
  'chart-area-smooth',
  'chart-area-stepper',
  'chart-average',
  'chart-bar-floating',
  'chart-bar-overlay',
  'chart-bar-stacked',
  'chart-bar-target',
  'chart-bubble',
  'chart-bubble-packed',
  'chart-bullet',
  'align-box-bottom-center',
  'align-box-middle-center',
  'align-box-top-center',
  'align-horizontal-center',
  'align-vertical-bottom',
  'align-vertical-center',
  'align-vertical-top',
  'arrange',
  'arrange-horizontal',
  'arrange-vertical',
  'build-tool',
  'calendar-settings',
  'calendar-tools',
  'delivery-settings',
  'desk-adjustable',
  'dfsort-ibm-zsort',
  'filter-edit',
  'align-box-bottom-left',
  'align-box-bottom-right',
  'align-box-middle-left',
  'align-box-middle-right',
  'align-box-top-left',
  'align-box-top-right',
  'align-horizontal-left',
  'align-horizontal-right',
  'arrow-down-left',
  'arrow-down-right',
  'arrow-shift-down',
  'arrow-up-left',
  'arrow-up-right',
  'arrows-horizontal',
  'arrows-vertical',
  'border-left',
  'border-right',
  'api-key',
  'block-storage',
  'block-storage-alt',
  'coupling-facility-encryption',
  'document-security',
  'encryption',
  'firewall-classic',
  'gateway-security',
  'gateway-vpn',
  'group-security',
  'hardware-security-module',
  'ibm-cloud-essential-security-and-observability-services',
  'ibm-cloud-ipsec-vpn',
  'ibm-cloud-key-protect',
  'ibm-cloud-pak-security',
  'ibm-cloud-security',
  'ibm-cloud-security-compliance-center',
  'api-1',
  'asset-digital-twin',
  'barcode',
  'bare-metal-server',
  'bare-metal-server-01',
  'bare-metal-server-02',
  'cics-transaction-server-zos',
  'cloud-alerting',
  'cloud-app',
  'cloud-auditing',
  'cloud-ceiling',
  'cloud-download',
  'cloud-foundry-1',
  'cloud-foundry-2',
  'cloud-logging',
  'cloud-monitoring',
  'cloud-offline',
  'archive',
  'base-document-set',
  'copy-file',
  'document-add',
  'document-attachment',
  'document-blank',
  'document-comment',
  'document-configuration',
  'document-epdf',
  'document-export',
  'document-horizontal',
  'document-import',
  'document-multiple-01',
  'document-multiple-02',
  'document-pdf',
  'document-preliminary',
  'document-processor',
  'arithmetic-median',
  'audio-console',
  'boot-volume',
  'boot-volume-alt',
  'build-image',
  'camera-action',
  'document-audio',
  'document-video',
  'drone-video',
  'ibm-cloud-vpc-images',
  'ibm-quantum-safe-remediator',
  'image-copy',
  'image-medical',
  'image-reference',
  'image-search',
  'image-search-alt',
  'image-service',
  'basketball',
  'face-wink',
  'face-wink-filled',
  'game-console',
  'game-wireless',
  'global-loan-and-trial',
  'row-insert',
  'tennis-ball',
  'traffic-flow-incident',
  'trophy',
  'trophy-filled',
  'winter-warning',
  'wintry-mix',
  'battery-error',
  'battery-warning',
  'calculator-check',
  'certificate-check',
  'checkbox',
  'checkbox-checked',
  'checkbox-checked-filled',
  'checkbox-indeterminate',
  'checkbox-indeterminate-filled',
  'checkmark-filled',
  'checkmark-filled-error',
  'checkmark-filled-warning',
  'checkmark-outline',
  'checkmark-outline-error',
  'checkmark-outline-warning',
  'cross-tab',
  'crossroads',
  'bus',
  'cabin-care',
  'cabin-care-alert',
  'cabin-care-alt',
  'calendar-heat-map',
  'car',
  'car-front',
  'carbon',
  'carbon-accounting',
  'carbon-for-aem',
  'carbon-for-ibm-dotcom',
  'carbon-for-ibm-product',
  'carbon-for-mobile',
  'carbon-for-salesforce',
  'carbon-ui-builder',
  'caret-sort',
  'carousel-horizontal',
  'business-processes',
  'currency',
  'currency-baht',
  'currency-dollar',
  'currency-euro',
  'currency-lira',
  'currency-pound',
  'currency-ruble',
  'currency-shekel',
  'currency-won',
  'currency-yen',
  'finance',
  'piggy-bank',
  'piggy-bank-slot',
  'receipt',
  'shopping-cart-clear',
  'shopping-cart-error',
  'crop-health',
  'health-cross',
  'hospital',
  'hospital-bed',
  'ibm-telehealth',
  'location-heart',
  'location-heart-filled',
  'reminder-medical',
  'watson-health',
  'alarm-subtract',
  'user-follow',
  'airport-01',
  'rewind-10',
  'notification-off-filled',
  'chart-candlestick',
  'filter-remove',
  'brightness-contrast',
  'ibm-cloud-security-compliance-center-workload-protection',
  'cloud-registry',
  'document-protected',
  'image-store-local',
  'event-warning',
  'carousel-vertical',
  'shopping-cart-minus',
  'anchor',
  'user-identification',
  'airport-02',
  'rewind-30',
  'phone-application',
  'chart-cluster-bar',
  'filter-reset',
  'bring-forward',
];

// Comprehensive mapping for commonly used icons
const iconMapping: Record<string, string> = {
  // Navigation
  'dashboard': 'Dashboard',
  'home': 'Home',
  'search': 'Search',
  'settings': 'Settings',
  'user': 'User',
  'notification': 'Notification',
  'menu': 'Menu',
  'close': 'Close',
  'arrow-left': 'ArrowLeft',
  'arrow-right': 'ArrowRight',
  'arrow-up': 'ArrowUp',
  'arrow-down': 'ArrowDown',
  'chevron-left': 'ChevronLeft',
  'chevron-right': 'ChevronRight',
  'chevron-up': 'ChevronUp',
  'chevron-down': 'ChevronDown',
  
  // Actions
  'add': 'Add',
  'edit': 'Edit',
  'delete': 'Delete',
  'save': 'Save',
  'cancel': 'Cancel',
  'refresh': 'Refresh',
  'download': 'Download',
  'upload': 'Upload',
  'share': 'Share',
  'copy': 'Copy',
  'paste': 'Paste',
  'cut': 'Cut',
  'undo': 'Undo',
  'redo': 'Redo',
  
  // Data & Analytics
  'chart-line': 'ChartLine',
  'chart-bar': 'ChartBar',
  'chart-pie': 'ChartPie',
  'chart-scatter': 'ChartScatter',
  'analytics': 'Analytics',
  'table': 'Table',
  'list': 'List',
  'grid': 'Grid',
  
  // Communication
  'email': 'Email',
  'chat': 'Chat',
  'phone': 'Phone',
  'video': 'Video',
  'microphone': 'Microphone',
  'camera': 'Camera',
  'send': 'Send',
  'reply': 'Reply',
  'forward': 'Forward',
  
  // Files & Documents
  'catalog': 'Catalog',
  'document': 'Document',
  'folder': 'Folder',
  'file': 'File',
  'image': 'Image',
  'video-camera': 'VideoCamera',
  'audio': 'Audio',
  'pdf': 'Pdf',
  'word': 'Word',
  'excel': 'Excel',
  'powerpoint': 'Powerpoint',
  
  // Security
  'lock': 'Lock',
  'unlock': 'Unlock',
  'shield': 'Shield',
  'key': 'Key',
  'password': 'Password',
  'security': 'Security',
  'vpn': 'Vpn',
  'firewall': 'Firewall',
  
  // Development
  'code': 'Code',
  'terminal': 'Terminal',
  'api': 'Api',
  'database': 'Database',
  'server': 'Server',
  'container': 'Container',
  'kubernetes': 'Kubernetes',
  'docker': 'Docker',
  
  // Business
  'user-multiple': 'UserMultiple',
  'group': 'Group',
  'organization': 'Organization',
  'building': 'Building',
  'location': 'Location',
  'calendar': 'Calendar',
  'time': 'Time',
  'money': 'Money',
  'shopping-cart': 'ShoppingCart',
  'shopping-bag': 'ShoppingBag',
  
  // Status
  'checkmark': 'Checkmark',
  'error': 'Error',
  'error-outline': 'ErrorOutline',
  'warning': 'Warning',
  'information': 'Information',
  'help': 'Help',
  'question-mark': 'QuestionMark',
  'success': 'Success',
  'error-filled': 'ErrorFilled',
  'warning-filled': 'WarningFilled',
  'information-filled': 'InformationFilled',
  'lightning': 'Lightning',
  
  // System
  'settings-adjust': 'SettingsAdjust',
  'settings-view': 'SettingsView',
  'settings-check': 'SettingsCheck',
  'settings-advanced': 'SettingsAdvanced',
  'system': 'System',
  'monitor': 'Monitor',
  'laptop': 'Laptop',
  'mobile': 'Mobile',
  'tablet': 'Tablet',
  'desktop': 'Desktop',
  
  // Weather & Time
  'sun': 'Sun',
  'moon': 'Moon',
  'cloud': 'Cloud',
  'rain': 'Rain',
  'snow': 'Snow',
  'wind': 'Wind',
  'temperature': 'Temperature',
  'clock': 'Clock',
  'timer': 'Timer',
  'alarm': 'Alarm',
  
  // Social
  'facebook': 'Facebook',
  'twitter': 'Twitter',
  'linkedin': 'Linkedin',
  'github': 'Github',
  'youtube': 'Youtube',
  'instagram': 'Instagram',
  'slack': 'Slack',
  'discord': 'Discord',
  
  // Utilities
  'filter': 'Filter',
  'sort': 'Sort',
  'zoom-in': 'ZoomIn',
  'zoom-out': 'ZoomOut',
  'full-screen': 'FullScreen',
  'exit-full-screen': 'ExitFullScreen',
  'maximize': 'Maximize',
  'minimize': 'Minimize',
  'resize': 'Resize',
  'move': 'Move',
  'rotate': 'Rotate',
  'scale': 'Scale',
  
  // Map & Drawing Tools
  'layers': 'Layers',
  'opacity': 'Opacity',
  'choropleth-map': 'Location',
  'ruler-alt': 'Analytics',
  'draw': 'Pen',
  'code-block': 'Terminal',
  'printer': 'Printer',
  
  // Accessibility
  'user-accessibility': 'UserAccessibility',
  'user-accessibility-color-filled': 'UserAccessibilityColorFilled',
  'system-theme': 'SystemTheme',
  'format-text-size': 'FormatTextSize',
  'format-text-family': 'FormatTextFamily',
  'format-palette': 'FormatPalette',
  'operations-reset': 'OperationsReset',
  'file-download': 'FileDownload',
  'file-upload': 'FileUpload',
  'navigation-close': 'NavigationClose',
  
  // Settings & Actions - these are already defined above
  
  // Carbon Design System Icons
  'weather-Lightning': 'WeatherLightning',
  'status-information': 'StatusInformation',
  'system-workflow-information': 'SystemWorkflowInformation',
  'Ai': 'Ai',
  'format-image': 'FormatImage',
  
  // Additional icons used in demos
  'star': 'Star',
  'navigation': 'Navigation',
  'accessibility': 'Accessibility',
  'screen-reader': 'ScreenReader',
  'color': 'Color',
  'form': 'Form',
  'overlay': 'Overlay',
  'button': 'Button',
  'status': 'Status',
  'content': 'Content',

  // Additional 300 Carbon icon mappings
  '4-k': '4K',
  '4-kfilled': '4KFilled',
  'accept-action-usage': 'AcceptActionUsage',
  'accessibility-alt': 'AccessibilityAlt',
  'accessibility-color': 'AccessibilityColor',
  'accessibility-color-filled': 'AccessibilityColorFilled',
  'accumulation-ice': 'AccumulationIce',
  'accumulation-precipitation': 'AccumulationPrecipitation',
  'action-definition': 'ActionDefinition',
  'action-usage': 'ActionUsage',
  'activity': 'Activity',
  'add-alt': 'AddAlt',
  'add-child-node': 'AddChildNode',
  'add-filled': 'AddFilled',
  'add-large': 'AddLarge',
  'add-parent-node': 'AddParentNode',
  'alarm-add': 'AlarmAdd',
  'account': 'Account',
  'gateway-user-access': 'GatewayUserAccess',
  'multiuser-device': 'MultiuserDevice',
  'person': 'Person',
  'person-favorite': 'PersonFavorite',
  'two-person-lift': 'TwoPersonLift',
  'user-access': 'UserAccess',
  'user-activity': 'UserActivity',
  'user-admin': 'UserAdmin',
  'user-avatar': 'UserAvatar',
  'user-avatar-filled': 'UserAvatarFilled',
  'user-avatar-filled-alt': 'UserAvatarFilledAlt',
  'user-certification': 'UserCertification',
  'user-favorite': 'UserFavorite',
  'user-favorite-alt': 'UserFavoriteAlt',
  'user-favorite-alt-filled': 'UserFavoriteAltFilled',
  'user-filled': 'UserFilled',
  'accumulation-rain': 'AccumulationRain',
  'ai-business-impact-assessment': 'AiBusinessImpactAssessment',
  'ai-financial-sustainability-check': 'AiFinancialSustainabilityCheck',
  'ai-generate': 'AiGenerate',
  'ai-governance-lifecycle': 'AiGovernanceLifecycle',
  'ai-governance-tracked': 'AiGovernanceTracked',
  'ai-governance-untracked': 'AiGovernanceUntracked',
  'ai-label': 'AiLabel',
  'ai-launch': 'AiLaunch',
  'ai-recommend': 'AiRecommend',
  'airline-digital-gate': 'AirlineDigitalGate',
  'airline-manage-gates': 'AirlineManageGates',
  'airline-passenger-care': 'AirlinePassengerCare',
  'airline-rapid-board': 'AirlineRapidBoard',
  'airplay': 'Airplay',
  'airplay-filled': 'AirplayFilled',
  'airport-location': 'AirportLocation',
  'accumulation-snow': 'AccumulationSnow',
  'decision-tree': 'DecisionTree',
  'earth': 'Earth',
  'earth-americas': 'EarthAmericas',
  'earth-americas-filled': 'EarthAmericasFilled',
  'earth-europe-africa': 'EarthEuropeAfrica',
  'earth-europe-africa-filled': 'EarthEuropeAfricaFilled',
  'earth-filled': 'EarthFilled',
  'earth-southeast-asia': 'EarthSoutheastAsia',
  'earth-southeast-asia-filled': 'EarthSoutheastAsiaFilled',
  'earthquake': 'Earthquake',
  'ibm-zenvironments-dev-sec-ops': 'IbmZEnvironmentsDevSecOps',
  'list-tree': 'ListTree',
  'moonrise': 'Moonrise',
  'moonset': 'Moonset',
  'palm-tree': 'PalmTree',
  'radar-weather': 'RadarWeather',
  'add-comment': 'AddComment',
  'calls': 'Calls',
  'calls-all': 'CallsAll',
  'calls-incoming': 'CallsIncoming',
  'chat-bot': 'ChatBot',
  'chat-launch': 'ChatLaunch',
  'chat-off': 'ChatOff',
  'chat-operational': 'ChatOperational',
  'comments': 'Comments',
  'headphones': 'Headphones',
  'logo-snapchat': 'LogoSnapchat',
  'logo-wechat': 'LogoWechat',
  'message-queue': 'MessageQueue',
  'notification-counter': 'NotificationCounter',
  'notification-filled': 'NotificationFilled',
  'notification-new': 'NotificationNew',
  'notification-off': 'NotificationOff',
  'aggregator-count-rows': 'AggregatorCountRows',
  'aggregator-recalculation': 'AggregatorRecalculation',
  'agriculture-analytics': 'AgricultureAnalytics',
  'analytics-custom': 'AnalyticsCustom',
  'analytics-reference': 'AnalyticsReference',
  'business-metrics': 'BusinessMetrics',
  'chart-area': 'ChartArea',
  'chart-area-smooth': 'ChartAreaSmooth',
  'chart-area-stepper': 'ChartAreaStepper',
  'chart-average': 'ChartAverage',
  'chart-bar-floating': 'ChartBarFloating',
  'chart-bar-overlay': 'ChartBarOverlay',
  'chart-bar-stacked': 'ChartBarStacked',
  'chart-bar-target': 'ChartBarTarget',
  'chart-bubble': 'ChartBubble',
  'chart-bubble-packed': 'ChartBubblePacked',
  'chart-bullet': 'ChartBullet',
  'align-box-bottom-center': 'AlignBoxBottomCenter',
  'align-box-middle-center': 'AlignBoxMiddleCenter',
  'align-box-top-center': 'AlignBoxTopCenter',
  'align-horizontal-center': 'AlignHorizontalCenter',
  'align-vertical-bottom': 'AlignVerticalBottom',
  'align-vertical-center': 'AlignVerticalCenter',
  'align-vertical-top': 'AlignVerticalTop',
  'arrange': 'Arrange',
  'arrange-horizontal': 'ArrangeHorizontal',
  'arrange-vertical': 'ArrangeVertical',
  'build-tool': 'BuildTool',
  'calendar-settings': 'CalendarSettings',
  'calendar-tools': 'CalendarTools',
  'delivery-settings': 'DeliverySettings',
  'desk-adjustable': 'DeskAdjustable',
  'dfsort-ibm-zsort': 'DfsortIbmZSort',
  'filter-edit': 'FilterEdit',
  'align-box-bottom-left': 'AlignBoxBottomLeft',
  'align-box-bottom-right': 'AlignBoxBottomRight',
  'align-box-middle-left': 'AlignBoxMiddleLeft',
  'align-box-middle-right': 'AlignBoxMiddleRight',
  'align-box-top-left': 'AlignBoxTopLeft',
  'align-box-top-right': 'AlignBoxTopRight',
  'align-horizontal-left': 'AlignHorizontalLeft',
  'align-horizontal-right': 'AlignHorizontalRight',
  'arrow-down-left': 'ArrowDownLeft',
  'arrow-down-right': 'ArrowDownRight',
  'arrow-shift-down': 'ArrowShiftDown',
  'arrow-up-left': 'ArrowUpLeft',
  'arrow-up-right': 'ArrowUpRight',
  'arrows-horizontal': 'ArrowsHorizontal',
  'arrows-vertical': 'ArrowsVertical',
  'border-left': 'BorderLeft',
  'border-right': 'BorderRight',
  'api-key': 'ApiKey',
  'block-storage': 'BlockStorage',
  'block-storage-alt': 'BlockStorageAlt',
  'coupling-facility-encryption': 'CouplingFacilityEncryption',
  'document-security': 'DocumentSecurity',
  'encryption': 'Encryption',
  'firewall-classic': 'FirewallClassic',
  'gateway-security': 'GatewaySecurity',
  'gateway-vpn': 'GatewayVpn',
  'group-security': 'GroupSecurity',
  'hardware-security-module': 'HardwareSecurityModule',
  'ibm-cloud-essential-security-and-observability-services': 'IbmCloudEssentialSecurityAndObservabilityServices',
  'ibm-cloud-ipsec-vpn': 'IbmCloudIpsecVpn',
  'ibm-cloud-key-protect': 'IbmCloudKeyProtect',
  'ibm-cloud-pak-security': 'IbmCloudPakSecurity',
  'ibm-cloud-security': 'IbmCloudSecurity',
  'ibm-cloud-security-compliance-center': 'IbmCloudSecurityComplianceCenter',
  'api-1': 'Api_1',
  'asset-digital-twin': 'AssetDigitalTwin',
  'barcode': 'Barcode',
  'bare-metal-server': 'BareMetalServer',
  'bare-metal-server-01': 'BareMetalServer_01',
  'bare-metal-server-02': 'BareMetalServer_02',
  'cics-transaction-server-zos': 'CicsTransactionServerZos',
  'cloud-alerting': 'CloudAlerting',
  'cloud-app': 'CloudApp',
  'cloud-auditing': 'CloudAuditing',
  'cloud-ceiling': 'CloudCeiling',
  'cloud-download': 'CloudDownload',
  'cloud-foundry-1': 'CloudFoundry_1',
  'cloud-foundry-2': 'CloudFoundry_2',
  'cloud-logging': 'CloudLogging',
  'cloud-monitoring': 'CloudMonitoring',
  'cloud-offline': 'CloudOffline',
  'archive': 'Archive',
  'base-document-set': 'BaseDocumentSet',
  'copy-file': 'CopyFile',
  'document-add': 'DocumentAdd',
  'document-attachment': 'DocumentAttachment',
  'document-blank': 'DocumentBlank',
  'document-comment': 'DocumentComment',
  'document-configuration': 'DocumentConfiguration',
  'document-epdf': 'DocumentEpdf',
  'document-export': 'DocumentExport',
  'document-horizontal': 'DocumentHorizontal',
  'document-import': 'DocumentImport',
  'document-multiple-01': 'DocumentMultiple_01',
  'document-multiple-02': 'DocumentMultiple_02',
  'document-pdf': 'DocumentPdf',
  'document-preliminary': 'DocumentPreliminary',
  'document-processor': 'DocumentProcessor',
  'arithmetic-median': 'ArithmeticMedian',
  'audio-console': 'AudioConsole',
  'boot-volume': 'BootVolume',
  'boot-volume-alt': 'BootVolumeAlt',
  'build-image': 'BuildImage',
  'camera-action': 'CameraAction',
  'document-audio': 'DocumentAudio',
  'document-video': 'DocumentVideo',
  'drone-video': 'DroneVideo',
  'ibm-cloud-vpc-images': 'IbmCloudVpcImages',
  'ibm-quantum-safe-remediator': 'IbmQuantumSafeRemediator',
  'image-copy': 'ImageCopy',
  'image-medical': 'ImageMedical',
  'image-reference': 'ImageReference',
  'image-search': 'ImageSearch',
  'image-search-alt': 'ImageSearchAlt',
  'image-service': 'ImageService',
  'basketball': 'Basketball',
  'face-wink': 'FaceWink',
  'face-wink-filled': 'FaceWinkFilled',
  'game-console': 'GameConsole',
  'game-wireless': 'GameWireless',
  'global-loan-and-trial': 'GlobalLoanAndTrial',
  'row-insert': 'RowInsert',
  'tennis-ball': 'TennisBall',
  'traffic-flow-incident': 'TrafficFlowIncident',
  'trophy': 'Trophy',
  'trophy-filled': 'TrophyFilled',
  'winter-warning': 'WinterWarning',
  'wintry-mix': 'WintryMix',
  'battery-error': 'BatteryError',
  'battery-warning': 'BatteryWarning',
  'calculator-check': 'CalculatorCheck',
  'certificate-check': 'CertificateCheck',
  'checkbox': 'Checkbox',
  'checkbox-checked': 'CheckboxChecked',
  'checkbox-checked-filled': 'CheckboxCheckedFilled',
  'checkbox-indeterminate': 'CheckboxIndeterminate',
  'checkbox-indeterminate-filled': 'CheckboxIndeterminateFilled',
  'checkmark-filled': 'CheckmarkFilled',
  'checkmark-filled-error': 'CheckmarkFilledError',
  'checkmark-filled-warning': 'CheckmarkFilledWarning',
  'checkmark-outline': 'CheckmarkOutline',
  'checkmark-outline-error': 'CheckmarkOutlineError',
  'checkmark-outline-warning': 'CheckmarkOutlineWarning',
  'cross-tab': 'CrossTab',
  'crossroads': 'Crossroads',
  'bus': 'Bus',
  'cabin-care': 'CabinCare',
  'cabin-care-alert': 'CabinCareAlert',
  'cabin-care-alt': 'CabinCareAlt',
  'calendar-heat-map': 'CalendarHeatMap',
  'car': 'Car',
  'car-front': 'CarFront',
  'carbon': 'Carbon',
  'carbon-accounting': 'CarbonAccounting',
  'carbon-for-aem': 'CarbonForAem',
  'carbon-for-ibm-dotcom': 'CarbonForIbmDotcom',
  'carbon-for-ibm-product': 'CarbonForIbmProduct',
  'carbon-for-mobile': 'CarbonForMobile',
  'carbon-for-salesforce': 'CarbonForSalesforce',
  'carbon-ui-builder': 'CarbonUiBuilder',
  'caret-sort': 'CaretSort',
  'carousel-horizontal': 'CarouselHorizontal',
  'business-processes': 'BusinessProcesses',
  'currency': 'Currency',
  'currency-baht': 'CurrencyBaht',
  'currency-dollar': 'CurrencyDollar',
  'currency-euro': 'CurrencyEuro',
  'currency-lira': 'CurrencyLira',
  'currency-pound': 'CurrencyPound',
  'currency-ruble': 'CurrencyRuble',
  'currency-shekel': 'CurrencyShekel',
  'currency-won': 'CurrencyWon',
  'currency-yen': 'CurrencyYen',
  'finance': 'Finance',
  'piggy-bank': 'PiggyBank',
  'piggy-bank-slot': 'PiggyBankSlot',
  'receipt': 'Receipt',
  'shopping-cart-clear': 'ShoppingCartClear',
  'shopping-cart-error': 'ShoppingCartError',
  'crop-health': 'CropHealth',
  'health-cross': 'HealthCross',
  'hospital': 'Hospital',
  'hospital-bed': 'HospitalBed',
  'ibm-telehealth': 'IbmTelehealth',
  'location-heart': 'LocationHeart',
  'location-heart-filled': 'LocationHeartFilled',
  'reminder-medical': 'ReminderMedical',
  'watson-health': 'WatsonHealth',
  'alarm-subtract': 'AlarmSubtract',
  'user-follow': 'UserFollow',
  'airport-01': 'Airport_01',
  'rewind-10': 'Rewind_10',
  'notification-off-filled': 'NotificationOffFilled',
  'chart-candlestick': 'ChartCandlestick',
  'filter-remove': 'FilterRemove',
  'brightness-contrast': 'BrightnessContrast',
  'ibm-cloud-security-compliance-center-workload-protection': 'IbmCloudSecurityComplianceCenterWorkloadProtection',
  'cloud-registry': 'CloudRegistry',
  'document-protected': 'DocumentProtected',
  'image-store-local': 'ImageStoreLocal',
  'event-warning': 'EventWarning',
  'carousel-vertical': 'CarouselVertical',
  'shopping-cart-minus': 'ShoppingCartMinus',
  'anchor': 'Anchor',
  'user-identification': 'UserIdentification',
  'airport-02': 'Airport_02',
  'rewind-30': 'Rewind_30',
  'phone-application': 'PhoneApplication',
  'chart-cluster-bar': 'ChartClusterBar',
  'filter-reset': 'FilterReset',
  'bring-forward': 'BringForward',
};

export const getCarbonIconName = (iconName: string): string => {
  // First check if we have a direct mapping
  if (iconMapping[iconName]) {
    return iconMapping[iconName];
  }
  
  // Fallback to the original transformation
  return iconName
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}; 